Feature/customized order
storekeeper-company/storekeeper-woocommerce-b2c pull request #153
Opened 2024-11-27 21:15 UTC by Danyellita

## What?
Customized orders (text & image).

## Why?

To enable business owners (particularly retailers who sell customizable products) to offer personalized orders. This feature will allow customers to personalize their purchases by adding custom text, images, logos, and other options to products such as cakes, T-shirts, and gift cards. The feature will enhance the customer experience by offering a higher degree of customization, particularly for gifting and special occasions.

## How?
Added php files for image/text addon options.

## Screenshots (optional)

(https://gyazo.com/86b0bede4601949bc56fb8b1e21e8d73)

2024-11-28 07:57 UTC, ikulis commented on resources/js/upload-image.js
> +                alert('Please select an image first.');
translations

2024-11-28 07:57 UTC, ikulis commented on resources/js/upload-image.js
> +                console.log(validationMessage);
```suggestion
```

2024-11-28 07:57 UTC, ikulis commented on resources/js/upload-image.js
> +                    validationMessage = `Image is too large. Maximum dimensions are ${maxWidth}x${maxHeight}.`;
transaltions

2024-11-28 07:57 UTC, ikulis commented on resources/js/upload-image.js
> +                            $('#success-message').text('Image uploaded successfully!').fadeIn();
translatioons

2024-11-28 07:57 UTC, ikulis commented on resources/js/upload-image.js
> +                        $(validationMessageId).html('<span style="color: red;">An error occurred while uploading the image.</span>');
translations

2024-11-28 07:57 UTC, ikulis commented on resources/js/upload-image.js
> +                            $(validationMessageId).html(`<span style="color: red;">${response.data.message}</span>`);
escape the message

2024-11-28 07:57 UTC, ikulis commented on src/StoreKeeper/WooCommerce/B2C/Core.php
> +//        add_filter('woocommerce_shipping_settings', 'displayMinAmountField');
?

2024-11-28 07:57 UTC, ikulis commented on src/StoreKeeper/WooCommerce/B2C/Core.php
> +            if (move_uploaded_file($uploaded_file['tmp_name'], $upload_path)) {
you need to check mime type if it's and image

2024-11-28 07:57 UTC, ikulis commented on src/StoreKeeper/WooCommerce/B2C/Frontend/Handlers/ProductAddOnHandler.php
> -            ) {
why was this removed ?

2024-11-28 07:57 UTC, ikulis commented on src/StoreKeeper/WooCommerce/B2C/Frontend/Handlers/ProductAddOnHandler.php
> +                        if (!empty($_POST['addon_text'][$addon['product_addon_group_id']][$option['id']]['required-text'])) {
```suggestion
$option_text = $_POST['addon_text'][$addon['product_addon_group_id']][$option['id']] ?? [];
                        if (!empty(option_text['required-text'])) {
```

2024-11-28 07:57 UTC, ikulis commented on src/StoreKeeper/WooCommerce/B2C/Frontend/Handlers/ProductAddOnHandler.php
> +                        if (!empty($_POST['addon_image'][$addon['product_addon_group_id']][$option['id']]['required-image'])) {
```suggestion
$option_image = $_POST['addon_image'][$addon['product_addon_group_id']][$option['id']] ?? [];
                        if (!empty($option_image['required-image'])) {
```

2024-11-28 07:57 UTC, ikulis commented on src/StoreKeeper/WooCommerce/B2C/Frontend/Handlers/ProductAddOnHandler.php
> +                            'image' => $addon_image,
```suggestion
                           self::CART_FIELD_TEXT=> $addon_text,
                           self::CART_FIELD_IMAGE => $addon_image,
```

2024-11-29 08:22 UTC, Danyellita commented on tests/unit/Exports/OrderExportTest.php
> +                if (isset($new_order['shipping_address_house_number'])) {
there was an error regarding this test for  'shipping_address_house_number' .

2024-12-05 22:26 UTC, jnmrclmbsjse requested changes
Mostly translations and escapes.
Please double check @ikulis review as well, you missed a bunch of it. Maybe you overlooked the hidden conversations.

![image](https://github.com/user-attachments/assets/e767cca2-8040-4197-85ae-217c05353ddd)

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/Frontend/Handlers/ProductAddOnHandler.php
> +            $has_add_ons = true;
```suggestion
            $selectedOptions = $this->getSelectedOptionFromPost();
            $cart_item_data[self::CART_FIELD_SELECTED_IDS] = $selectedOptions;
            $has_add_ons = !empty($selectedOptions);
```
Probably better.

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/optional-image.php
> +        <input type="checkbox" name="agree" id="agree-images"> <strong>' . __('Would you like an image on the product?', I18N::DOMAIN) . '</strong>
```suggestion
        <input type="checkbox" name="agree" id="agree-images"> <strong>' . esc_html__('Would you like an image on the product?', I18N::DOMAIN) . '</strong>
```

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/optional-image.php
> +            : ' (' . __('free', I18N::DOMAIN) . ')') .
```suggestion
            : ' (' . esc_html__('free', I18N::DOMAIN) . ')') .
```

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/optional-image.php
> +    echo '<br><button type="button" class="upload-image-btn" data-option-id="' . esc_attr($option['id']) . '">Upload Image</button>';
Translation
```suggestion
    echo '<br><button type="button" class="upload-image-btn" data-option-id="' . esc_attr($option['id']) . '">'.esc_html__('Upload Image', I18N::DOMAIN').'</button>';
```

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/optional-image.php
> +        <h2><?php echo __(
```suggestion
        <h2><?php echo esc_html__(
```

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/optional-image.php
> +            <?php echo __(
```suggestion
            <?php echo esc_html__(
```

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/optional-text.php
> +        <input type="checkbox" name="agree" id="agree"> <strong>'. __(
```suggestion
        <input type="checkbox" name="agree" id="agree"> <strong>'. esc_html__(
```

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/required-image.php
> +        <input type="checkbox" name="agree" id="agree" checked disabled> <strong>' . __('Required Image', I18N::DOMAIN) . '</strong>
```suggestion
        <input type="checkbox" name="agree" id="agree" checked disabled> <strong>' . esc_html__('Required Image', I18N::DOMAIN) . '</strong>
```

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/required-image.php
> +            : ' (' . __('free', I18N::DOMAIN) . ')') .
```suggestion
            : ' (' . esc_html__('free', I18N::DOMAIN) . ')') .
```

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/required-image.php
> +    echo '<br><button type="button" class="upload-image-btn" data-option-id="' . esc_attr($option['id']) . '">Upload Image</button>';
```suggestion
    echo '<br><button type="button" class="upload-image-btn" data-option-id="' . esc_attr($option['id']) . '">'.esc_html__('Upload Image', I18N::DOMAIN).'</button>';
```

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/required-image.php
Looks almost identical to `src/StoreKeeper/WooCommerce/B2C/templates/add-on/optional-image.php`, maybe can be improved?

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/required-text.php
> +        <strong style="vertical-align: middle">' . __(
```suggestion
        <strong style="vertical-align: middle">' . esc_html__(
```

2024-12-05 22:26 UTC, jnmrclmbsjse commented on tests/unit/Exports/OrderExportTest.php
> +                if (isset($new_order['shipping_address_house_number'])) {
What's the actual error? Maybe it needs fixing in code rather than test.

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/required-text.php
> +            : ' (' . __('free', I18N::DOMAIN) . ')') .
```suggestion
            : ' (' . esc_html__('free', I18N::DOMAIN) . ')') .
```

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/optional-text.php
> +            : ' (' . __('free',  I18N::DOMAIN) . ')') .
```suggestion
            : ' (' . esc_html__('free',  I18N::DOMAIN) . ')') .
```

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/required-image.php
> +        <h2><?php echo __(
```suggestion
        <h2><?php echo esc_html__(
```

2024-12-05 22:26 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/templates/add-on/required-image.php
> +            <?php echo __(
```suggestion
            <?php echo esc_html__(
```

2024-12-06 09:14 UTC, Danyellita commented on tests/unit/Exports/OrderExportTest.php
> +                if (isset($new_order['shipping_address_house_number'])) {
@jnmrclmbsjse, @ikulis the error - > ![image](https://github.com/user-attachments/assets/ab3e873d-1c99-40b6-a908-8300cc230b4c)

Will check it in code to fix it.

2024-12-06 20:38 UTC, jnmrclmbsjse requested changes
A few more

2024-12-06 20:38 UTC, jnmrclmbsjse commented on src/StoreKeeper/WooCommerce/B2C/Core.php
> +                $image_url = $uploadDir['url'].'/'.basename($uploadedFile['name']);
This is an ajax action, wp_redirect is not appropriate
```suggestion
            if (!in_array($fileMimeType, $allowedMimeTypes)) {
                wp_send_json_error(['message' => esc_html__('Invalid file type', I18N::DOMAIN)]);
            } else if (move_uploaded_file($uploadedFile['tmp_name'], $uploadPath)) {
                $image_url = $uploadDir['url'].'/'.basename($uploadedFile['name']);
```

2024-12-06 20:38 UTC, jnmrclmbsjse commented on tests/unit/Exports/OrderExportTest.php
> +                if (isset($new_order['shipping_address_house_number'])) {
Yes please check @Danyellita , I tried running the test from my end and it works without these changes

2024-12-12 05:57 UTC, jnmrclmbsjse approved these changes

2024-12-12 08:01 UTC, merged